attention_head_size: 1
categorical_groups: {}
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 4
hidden_continuous_sizes: {}
hidden_size: 4
learning_rate: 0.05
log_gradient_flow: false
log_interval: -1
log_val_interval: null
lstm_layers: 1
max_encoder_length: 20
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
  center: true
  eps: 1.0e-08
  groups: []
  method: standard
  norm_:
    center: !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      OmlkMRgySz8=
    scale: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      4XgJfmtxkz8=
  scale_by_group: false
  transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals:
- encoder_length
- Open_center
- Open_scale
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- relative_time_idx
time_varying_reals_encoder:
- relative_time_idx
- High
- Low
- Close
- Volume
weight_decay: 0.0
x_categoricals: []
x_reals:
- encoder_length
- Open_center
- Open_scale
- relative_time_idx
- High
- Low
- Close
- Volume
